name: Juice Shop Security Scan

# Triggers the workflow on push or pull requests to the master branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Permissions required for security events (e.g., uploading Trivy SARIF to GitHub Security tab)
permissions:
  security-events: write
  contents: read

jobs:
  # SonarQube scan for code quality and security
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for SonarQube to analyze full history

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Juice Shop requires Node.js

      - name: Install SonarQube Scanner
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner --version

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=juice-shop \
            -Dsonar.projectName="Juice Shop" \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.sources=. \
            -Dsonar.exclusions="**/node_modules/**,**/test/**" \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        continue-on-error: false # Fail the job if SonarQube scan fails
