name: Seguridad CI

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Trivy (para escaneo de vulnerabilidades)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Ejecutar Trivy (Escanear dependencias)
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Instalar ggshield
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install ggshield

      - name: Instalar TruffleHog
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install truffleHog

      - name: Ejecutar TruffleHog para escanear secretos
        run: |
          trufflehog --json --max_depth 50 --since_commit HEAD .
          
      - name: Instalar OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
          tar -xvzf ZAP_2.11.0_Linux.tar.gz
          cd ZAP_2.11.0_Linux
          ./zap.sh -daemon -port 8080

      - name: Ejecutar OWASP ZAP
        run: |
          curl -fsSL https://github.com/zaproxy/zaproxy/raw/master/scripts/quickstart.py | python3

      - name: Resultado del pipeline
        run: echo "El pipeline de seguridad ha terminado correctamente"
