name: Seguridad CI

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Trivy (para escaneo de vulnerabilidades)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Ejecutar Trivy (Escanear dependencias)
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog to scan for secrets
        run: |
          trufflehog --json --max_depth 50 --since_commit HEAD .

      # Opción 1: Instalación manual de OWASP ZAP
      - name: Instalar dependencias para OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre wget

      - name: Descargar e instalar OWASP ZAP
        run: |
          # Descargar el script de instalación
          wget --max-redirect=10 -O zap.sh https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2_15_0_unix.sh
          # Verificar que el archivo se descargó
          ls -la zap.sh
          # Mostrar las primeras líneas para depuración
          head -n 10 zap.sh
          # Hacer el script ejecutable
          chmod +x zap.sh
          # Forzar instalación no interactiva
          echo "o" | sudo ./zap.sh -q -dir /opt/zap -installdir /opt/zap
          # Verificar instalación
          ls -la /opt/zap
          /opt/zap/zap.sh -version || echo "Error: No se pudo ejecutar zap.sh"

      # Opción 2: Usar Docker para OWASP ZAP (comentar Opción 1 si usas esta)
      # - name: Ejecutar OWASP ZAP Baseline Scan con Docker
      #   run: |
      #     docker run --rm -v $(pwd):/zap/wrk owasp/zap2docker-stable \
      #     zap-baseline.py -t https://your-app-url.com -r zap_report.html

      - name: Ejecutar OWASP ZAP Baseline Scan
        run: |
          /opt/zap/zap.sh -cmd -quickurl https://your-app-url.com -quickout zap_report.html
        env:
          ZAP_QUICKOUT: zap_report.html

      - name: Subir reporte de OWASP ZAP como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
        if: always()

      - name: Resultado del pipeline
        run: echo "El pipeline de seguridad ha terminado correctamente"
