name: Seguridad CI

on:
  push:
    branches:
      - main

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Ejecutar Trivy (dependencias)
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog
        run: trufflehog --json --max_depth 50 --since_commit HEAD .

      - name: Generar métricas de vulnerabilidades (OWASP SAMM)
        run: |
          # Contar vulnerabilidades críticas de Trivy
          TRIVY_COUNT=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity == "CRITICAL" or .Severity == "HIGH")] | length' trivy_report.json)
          echo "Vulnerabilidades críticas en dependencias: $TRIVY_COUNT"
          # Contar vulnerabilidades de ZAP
          ZAP_COUNT=$(jq '[.site[].alerts[] | select(.risk == "High" or .risk == "Medium")] | length' zap_report.json)
          echo "Vulnerabilidades en la aplicación web: $ZAP_COUNT"
          # Registrar métricas en un archivo
          echo "{\"trivy_vulns\": $TRIVY_COUNT, \"zap_vulns\": $ZAP_COUNT}" > metrics.json

      - name: Subir métricas como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: security-metrics
          path: metrics.json
        if: always()

      - name: Crear issues en GitHub para vulnerabilidades críticas
        if: failure()  # Ejecutar solo si el pipeline falla (vulnerabilidades críticas o secretos detectados)
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const trivyReport = JSON.parse(fs.readFileSync('trivy_report.json'));
            const zapReport = JSON.parse(fs.readFileSync('zap_report.json'));
            const trufflehogReport = JSON.parse(fs.readFileSync('trufflehog_report.json'));

            let issues = [];

            // Vulnerabilidades críticas de Trivy
            trivyReport.Results?.forEach(result => {
              result.Vulnerabilities?.forEach(vuln => {
                if (vuln.Severity === 'CRITICAL' || vuln.Severity === 'HIGH') {
                  issues.push({
                    title: `Vulnerabilidad crítica detectada: ${vuln.VulnerabilityID}`,
                    body: `**CVE**: ${vuln.VulnerabilityID}\n**Severidad**: ${vuln.Severity}\n**Paquete**: ${vuln.PkgName}\n**Descripción**: ${vuln.Description}\nAcción requerida: Actualizar o mitigar.`
                  });
                }
              });
            });

            // Vulnerabilidades de ZAP
            zapReport.site?.forEach(site => {
              site.alerts?.forEach(alert => {
                if (alert.risk === 'High') {
                  issues.push({
                    title: `Vulnerabilidad web detectada: ${alert.name}`,
                    body: `**Riesgo**: ${alert.risk}\n**Descripción**: ${alert.desc}\n**Solución**: ${alert.solution}\nAcción requerida: Implementar corrección.`
                  });
                }
              });
            });

            // Secretos de TruffleHog
            if (trufflehogReport.length > 0) {
              issues.push({
                title: `Secretos detectados en el repositorio`,
                body: `Se encontraron secretos en el código. Revisar el reporte 'trufflehog_report.json' para detalles. Acción requerida: Rotar las claves comprometidas.`
              });
            }

            // Crear issues
            for (const issue of issues) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issue.title,
                body: issue.body
              });
            }

      - name: Resultado del pipeline
        run: echo "El pipeline de seguridad ha terminado correctamente"

