name: Seguridad CI

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Trivy (para escaneo de vulnerabilidades)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Ejecutar Trivy (Escanear dependencias)
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog to scan for secrets
        run: |
          trufflehog --json --max_depth 50 --since_commit HEAD .

      - name: Instalar OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          curl -sL https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2_14_0_unix.sh -o zap.sh
          chmod +x zap.sh
          sudo ./zap.sh -cmd -silent -quickinstall

      - name: Ejecutar OWASP ZAP Baseline Scan
        run: |
          /opt/zaproxy/zap.sh -cmd -quickurl https://your-app-url.com -quickout zap_report.html
        env:
          ZAP_QUICKOUT: zap_report.html

      - name: Subir reporte de OWASP ZAP como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html

      - name: Resultado del pipeline
        run: echo "El pipeline de seguridad ha terminado correctamente"
