name: Seguridad CI

on:
  push:
    branches:
      - main

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Ejecutar Trivy (dependencias)
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Escanear imagen de Juice Shop con Trivy
        run: |
          docker pull bkimminich/juice-shop
          trivy image --exit-code 1 --severity HIGH,CRITICAL bkimminich/juice-shop

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog
        run: trufflehog --json --max_depth 50 --since_commit HEAD . --fail

      - name: Verificar accesibilidad de la URL
        run: |
          curl -I https://juice-shop.herokuapp.com

      - name: Ejecutar OWASP ZAP Baseline Scan con Docker
        run: |
          docker run --rm -v $(pwd):/zap/wrk owasp/zap2docker-stable \
          zap-baseline.py -t https://juice-shop.herokuapp.com -r zap_report.html -m 5 -d -I

      - name: Subir reporte de OWASP ZAP como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
        if: always()

      - name: Resultado del pipeline
        run: echo "El pipeline de seguridad ha terminado correctamente"
