name: Seguridad CI

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Trivy (para escaneo de vulnerabilidades)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Ejecutar Trivy (Escanear dependencias)
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog to scan for secrets
        run: |
          trufflehog --json --max_depth 50 --since_commit HEAD .
          
      - name: Download and extract OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
          tar -xvzf ZAP_2.11.1_Linux.tar.gz
          cd ZAP_2.11.1

      # Run OWASP ZAP with the selected parameters
      - name: Run OWASP ZAP
        run: |
          cd ZAP_2.11.1
          ./zap.sh -daemon -port 8080 # Puedes cambiar parámetros según tus necesidades

      # Optional: You can add here a custom scan with ZAP API (as an example)
      - name: Perform ZAP Scan
        run: |
          curl -X GET "http://localhost:8080/JSON/ascan/action/scan?url=http://example.com&maxDepth=5"

      # Optional: Upload ZAP results as artifact
      - name: Upload ZAP results
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-results
          path: ./ZAP_2.11.1/owasp-zap-report.html

      - name: Resultado del pipeline
        run: echo "El pipeline de seguridad ha terminado correctamente"
