name: Seguridad CI

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  seguridad:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Trivy (para escaneo de vulnerabilidades)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Ejecutar Trivy (Escanear dependencias)
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL .

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog to scan for secrets
        run: |
          trufflehog --json --max_depth 50 --since_commit HEAD .
          
      # Download and extract OWASP ZAP weekly build
      - name: Download OWASP ZAP Weekly Build
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/w2025-04-30/ZAP_WEEKLY_D-2025-04-30.zip
          # List contents of the ZIP file before extracting
          unzip -l ZAP_WEEKLY_D-2025-04-30.zip
          unzip ZAP_WEEKLY_D-2025-04-30.zip
          # List the extracted files
          ls -R

      # Check if the ZAP directory exists after extraction
      - name: Check if ZAP directory exists
        run: |
          if [ -d "ZAP_WEEKLY_D-2025-04-30" ]; then
            echo "Directory exists"
          else
            echo "Directory does not exist"
            exit 1
          fi

      # Run OWASP ZAP in daemon mode
      - name: Run OWASP ZAP
        run: |
          cd ZAP_WEEKLY_D-2025-04-30
          ./zap.sh -daemon -port 8080

      # Perform security scan (example scanning localhost, replace URL as needed)
      - name: Perform ZAP Scan
        run: |
          curl -X GET "http://localhost:8080/JSON/ascan/action/scan?url=http://example.com&maxDepth=5"

      # Optional: Upload ZAP results as artifact
      - name: Upload ZAP results
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-results
          path: ./ZAP_2.11.1/owasp-zap-report.html

      - name: Resultado del pipeline
        run: echo "El pipeline de seguridad ha terminado correctamente"
