name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Usamos la última versión de checkout

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v2  # Asegúrate de usar v2 o la versión más reciente
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-sonar-cache-

    - name: Build with Maven
      run: mvn clean install

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        organization: 'my-organization'  # Reemplaza con tu organización
        projectKey: 'my-project-key'    # Reemplaza con tu clave de proyecto
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Asegúrate de agregar tu token en Secrets


