name: SonarCloud Scan

on:
  push:
    branches:
      - main  # O la rama que quieres escanear
  pull_request:
    branches:
      - main  # O la rama de destino para los PRs

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}  # Se usa el token de SonarCloud desde los secretos de GitHub
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

