name: SonarCloud Scan

on:
  push:
    branches:
      - main  # O la rama que quieres escanear
  pull_request:
    branches:
      - main  # O la rama de destino para los PRs

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Ejecutar el escaneo de SonarCloud
      - name: Run SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          entryPoint: "sonar-scanner"
          args: "-Dsonar.login=${{ secrets.SONAR_TOKEN }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


