name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Asegúrate de estar usando la última versión de checkout

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'   # Especifica la distribución (temurin es la opción recomendada)
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: 'success'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v3  # Usamos la versión más reciente de actions/cache
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-sonar-cache-

        # Paso 3: Escaneo con SonarCloud (Sin hacer build)
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        organization: 'libra´s'  # Reemplaza con tu organización de SonarCloud
        projectKey: '3e26a42aca28dc44ef590410d141a9cea1d0802a'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Agrega tu token en los secretos

