name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # o la versión que use Juice Shop

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Run tests with coverage
        run: npm run test -- --coverage --watchAll=false

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=juice-shop
            -Dsonar.projectName="OWASP Juice Shop"
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,bower_components/**,dist/**,coverage/**,**/*.spec.ts
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.host.url=http://localhost:9000  # Aquí se usa localhost:9000


      - name: Upload SonarQube Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report
          path: path_to_your_report/sonar-report.json 
