name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del c贸digo
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configuraci贸n de Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Especificamos la distribuci贸n de Java
      # Paso 3: SonarCloud Scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v5
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: your_project_key # Reemplaza por tu project key
          sonar-organization: your_organization_key # Reemplaza por tu organizaci贸n en SonarCloud

