name: SonarCloud Scan

on:
  push:
    branches:
      - main  # O la rama que quieres escanear
  pull_request:
    branches:
      - main  # O la rama de destino para los PRs

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 3: Ejecutar el análisis de SonarCloud con depuración
      - name: Run SonarCloud Scan with Debug
        run: |
          sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
