name: SonarCloud

on:
  push:
    branches:
      - main   # O el nombre de la rama que desees analizar
  pull_request:
    branches:
      - main   # O el nombre de la rama que desees analizar

jobs:
  sonarcloud:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-sonar-cache-

    - name: Build with Maven
      run: mvn clean install

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        organization: 'my-organization'  # Reemplaza con tu organización de SonarCloud
        projectKey: 'my-project-key'    # Reemplaza con tu clave de proyecto de SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Asegúrate de agregar el token como secret en GitHub


