name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Permite ejecutar manualmente desde la UI de GitHub
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Web Application
    steps:
      # Clona el repositorio
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      # Ejecuta el escaneo baseline de ZAP
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:80' # Cambia por tu URL objetivo
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          issue_title: 'ZAP Baseline Scan Report'
          fail_action: false
          allow_issue_writing: true
          artifact_name: 'zap_scan'
